linux-blktests/blktests

- tests/block/006
There is no 'blocking' parameter on some branches, eg. RHEL7.
Signed-off-by: Xiao Liang <xiliang@redhat.com>
> block/006: added checking if null_blk has blocking flag

- tests/block/006
- tests/block/008
- tests/block/010
Add the missed _have_fio for block/006, block/008, block/010
Signed-off-by: Yi Zhang <yi.zhang@redhat.com>
> block/006, block/008, block/010: add _have_fio to require function

- common/cpuhotplug
Due to the missing plus, only the last cpu in directory listing was used in hotpluggable cpus.
> Append not replace cpus to cpus hotplug list

- .dir-locals.el
Add a dir-locals.el so Emacs will do the right thing when editing
blktests code and test cases.
Signed-off-by: Johannes Thumshirn <jthumshirn@suse.de>
> dir-locals.el: add emacs local variable config

- tests/sg/003
- tests/sg/003.out
Add a regression test for the patch "scsi: sd: Keep disk read-only when
re-reading partition"[0] which ensures re-reading a disk's partition table
doesn't change its read-only flag.
[0] https://www.spinics.net/lists/linux-scsi/msg118162.html
> sg: test for patch "Keep disk read-only when re-reading partition"

- common/null_blk
- tests/block/006
- tests/block/010
- tests/block/014
- tests/block/015
- tests/block/016
- tests/block/017
- tests/block/018
- tests/block/020
- tests/block/021
- tests/block/022
Hi,
I am not sure it happens only on my machines but I often have "modprobe: FATAL: Module null_blk is in use." error.
So I adds "udevadm settle" before unloading null_blk module.
Second and third pathes create and apply common helpers for using null_blk module.
They do not fix anything.
> settle udev before unloading null_blk

- src/sg/syzkaller1.c
How mmap is mapped to a raw system call varies across different
architectures.  On some architectures (such as 32-bit ARM), __NR_mmap
may not exist at all; glibc will use __NR_mmap2 to implement mmap(2).
Syzkaller is using mmap() as a non-portable version of malloc(3), so
it should be safe to use the glibc's mmap wrapper instead of trying to
directly call the system call.
Signed-off-by: Theodore Ts'o <tytso@mit.edu>
Reviewed-by: Bart Van Assche <bvanassche@acm.org>
[ I found this when trying to build blktests as part of the kvm-xfstests test appliance, which I currently do for the x86_64, i386, arm64, and armhf platforms. ]
> src/sg/syzkaller1.c: fix portability problem for syscall(__NR_mmap, ...)

- README.md
Hello,
This PR adds two minor improvements to README, completing the information about the packages names and emphasize that those tests can destroy data before showing how to use the tool.
Thanks!
> README: stress warning and add "multipath-tools" information

- src/sg/syzkaller1.c
Thanks for making this code available. I tried to compile your tools on RISCV and found an unnecessary reference to linux/kvm.h
Your comments would be appreciated.
> linux/kvm.h appears to be unnecessary (and is x86 specific)

- tests/block/013
Hello,
While using `blktests`, I have found the following output for 013:
```
> ./check block/013
block/013 => sda (try BLKRRPART on a mounted device)         [failed]
runtime  3.916s  ...  2.772s
--- tests/block/013.out	2019-10-04 23:01:38.410271508 +0000
+++ /root/host/blktests/results/sda/block/013.out.bad	2019-10-22 14:34:25.669382490 +0000
@@ -1,3 +1,4 @@
Running block/013
-Device or resource busy
+grep: (standard input): No such file or directory
+blockdev: ioctl error on BLKRRPART: Device or resource busy
Test complete
```
It's clear that the test had been successful, despite the result of the test. The `grep` action that failed to proper parse the output from `blockdev` operation.
I could not reproduce this error outside `check` script, which makes me believe that some kind of …
> Improve test block/013

- tests/srp/rc
Linux kernel commit 569334014370 ("scsi: core: Delete scsi_use_blk_mq")
removed the use_blk_mq sysfs attribute. Hence only write into the
use_blk_mq sysfs attribute if it exists.
> tests/srp/rc: Make the SRP tests pass against kernel v5.7

- common/multipath-over-rdma
for the srp first run where /path/to/blktests/results is empty, it will
throw errors like:
$ ./check srp/001 srp/002 srp/003 srp/004 srp/005 srp/006 srp/007 srp/008 srp/009 srp/010 srp/011 srp/012 srp/013 srp/015
srp/001 (Create and remove LUNs)----------------------------
srp/001 (Create and remove LUNs)                             [failed]
==> /tmp/stderr <==
./check: line 275: LAST_TEST_RUN["$key"]: unbound variable
==> /tmp/stdout <==
--- tests/srp/001.out>------2020-06-09 13:44:19.000000000 +0800
+++ /lkp/benchmarks/blktests/results/nodev/srp/001.out.bad>-2020-06-09 16:18:22.594012394 +0800
@@ -1,3 +1,4 @@
Configured SRP target driver
+tests/srp/rc: line 105: use_blk_mq: Permission denied
count_luns(): 3 <> 3
Passed
Signed-off-by: Li Zhijian <zhijianx.li@intel.com>
> Fix ./check: line 275: LAST_TEST_RUN["$key"]: unbound variable

- tests/srp/rc
Instead of passing an empty string as argument to dd, do not pass any
argument when not using direct I/O.
Fixes: 577caa7d2b4a ("Fix unquoted integer shellcheck errors")
> tests/srp/rc: Do not pass an empty string to dd

- tests/block/008
- tests/block/019
- tests/nvme/032
Zoned devices should have no issues running block/{008,019} and
nvme/032, so mark the tests with CAN_BE_ZONED=1.
Signed-off-by: Klaus Jensen <k.jensen@samsung.com>
> tests: mark tests with CAN_BE_ZONED=1

- tests/srp/rc
Fix the following shellcheck warning:
tests/srp/rc:519:11: warning: The = here is literal. To assign by index, use
( [index]=value ) with no spaces. To keep as literal, quote it. [SC2191]
Reported-by: Shin'ichiro Kawasaki
> tests/srp/rc: Fix a shellcheck warning

- tests/nvme/rc
A failed connection will cause the later endless loop, so we should return
directly in such case.
344 _nvmet_passthru_target_connect() {
345         local trtype=$1
346         local subsys_name=$2
347
348         _nvme_connect_subsys "${trtype}" "${subsys_name}" || return
349         nsdev=$(_find_nvme_passthru_loop_dev "${subsys_name}")
350
351         # The following tests can race with the creation
352         # of the device so ensure the block device exists
353         # before continuing
354         while [ ! -b "${nsdev}" ]; do sleep 1; done <<< endless loop
355
356         echo "${nsdev}"
357 }
Signed-off-by: Li Zhijian <lizhijian@fujitsu.com>
> tests/nvme/rc: Fix possible endless loop

- tests/loop/008
- tests/loop/008.out
Add test for setting up a raw disk image with a GPT and ESP.
This is a regression test for commit b9684a71fca7
("block, loop: support partitions without scanning").
Signed-off-by: Michael Schaller <misch@google.com>
> loop: Add test to setup GPT and ESP on raw disk image

- common/rc
unset previous SKIP_REASON could cause a false failure.
nvme/033 => nvme0n1 (create and connect to an NVMeOF target with a passthru controller) [failed]
runtime  2.383s  ...  0.376s
--- tests/nvme/033.out      2022-06-08 08:46:27.956692453 +0000
+++ /home/lizhijian/blktests/results/nvme0n1/nvme/033.out.bad       2022-06-15 06:32:31.131001276 +0000
@@ -1,3 +1,8 @@
Running nvme/033
-NQN:blktests-subsystem-1 disconnected 1 controller(s)
+tests/nvme/rc: line 181: nvme: command not found
+tests/nvme/033: line 19: nvme: command not found
+tests/nvme/033: line 20: nvme: command not found
+tests/nvme/033: line 19: nvme: command not found
+tests/nvme/033: line 20: nvme: command not found
...
(Run 'diff -u tests/nvme/033.out /home/lizhijian/blktests/results/nvme0n1/nvme/033.out.bad' to see the …
> common/rc: don't unset previous SKIP_REASON in _have_kernel_option()

- tests/nvme/041
- tests/nvme/041.out
- tests/nvme/042
- tests/nvme/042.out
- tests/nvme/043
- tests/nvme/043.out
- tests/nvme/044
- tests/nvme/044.out
- tests/nvme/045
- tests/nvme/045.out
- tests/nvme/rc
This is a testsuite for the upcoming NVMe In-Band authentication. Clearly it depends on the code being merged with upstream, but nevertheless I've prepared the pull request now to give people a chance to test the new code.
nvme-cli has already been updated, so you just need to ensure you're running a newer (>= 2.0) version of nvme-cli.
It supersedes the previous pull request https://github.com/osandov/blktests/pull/97.
> Testsuite for nvme in-band authentication

- tests/srp/016
- tests/srp/016.out
Kernel commit 8fe4ce5836e9 ("scsi: core: Fix a use-after-free"; v6.0-rc5) fixes a kernel crash triggered by RDMA hot-unplug. This test triggers RDMA hot-unplug and also triggers a kernel crash without the aforementioned kernel commit.
Cc: Li Zhijian <lizhijian@fujitsu.com>
> srp/016: Add a test that triggers RDMA hot-unplug

- Makefile
- common/multipath-over-rdma
- common/null_blk
- tests/block/002
- tests/nvmeof-mp/rc
- tests/scsi/007
- tests/srp/014
- tests/srp/rc
- tests/zbd/003
- tests/zbd/rc
Suppress three shellcheck warnings: two warnings that are not useful and another warning that is reported in contexts where it does not apply.
> Fix multiple shellcheck warnings

- common/null_blk
_init_null_blk() passes an empty string as last argument to modprobe if RUN_FOR_ZONED is false. Fix this.
Fixes: e840e1537dc6 ("config: Introduce RUN_ZONED_TESTS variable and CAN_BE_ZONED flag")
> common/null_blk: Do not pass an empty string to modprobe

- tests/nvme/041
- tests/nvme/041.out
- tests/nvme/042
- tests/nvme/043
- tests/nvme/044
- tests/nvme/044.out
- tests/nvme/045
- tests/nvme/rc
I've picked up @hreinecke's work started in #100 (I think we can close it). I've address the feedback and fixed also the shellcheck reports (though this was against an older version of this tool)
~~The recently released version of shellcheck is reporting a bunch of new warning (as you are already aware of it: #107). So this PR wont pass the test though yet (waiting for the resolve from #107) Hence I mark this as just as draft.~~
The aim is to get my 'new' test working: https://lore.kernel.org/linux-nvme/20220913065758.134668-1-dwagner@suse.de/
> Enable 'fc' as transport for blktests (v2)

- common/iopoll
- tests/block/007
Linux kernel commit a614dd228035 ("block: don't allow writing to the poll queue attribute") makes writes into /sys/block/*/queue/io_poll a no-op. Rework test block/007 such that it no longer uses that attribute.
> tests/block/007: Rework I/O polling

- src/discontiguous-io.cpp
Fix the following build error:
g++  -O2 -std=c++11 -Wall -Wextra -Wshadow -Wno-sign-compare -Werror -DHAVE_LINUX_BLKZONED_H -o discontiguous-io discontiguous-io.cpp discontiguous-io.cpp: In function ‘void dumphex(std::ostream&, const void*, size_t)’: discontiguous-io.cpp:92:24: error: ‘uintptr_t’ was not declared in this scope
> src/discontiguous-io.cpp: Fix the build

- tests/nvme/002.out
- tests/nvme/016.out
- tests/nvme/017.out
With TP8013 the discovery log includes now a record for the discovery subsystem itself, so we need to update the blktests to be aware of the new discovery log page layout.
Signed-off-by: Hannes Reinecke <hare@suse.de>
> Update tests for discovery log page changes

- src/Makefile
Something external may set some special LDFLAGS. Currently those would get ignored. Lets honor them and pass them to the compiler.
This simplifies packaging and cross-compilation.
> src/Makefile: forward LDFLAGS to $(CC)

- tests/nvme/rc
With commit [1], the nvme connect command will show the connect msg which breaks blktests nvme/ related cases[2], fix it from blktests side.
[1]
https://github.com/linux-nvme/nvme-cli/commit/0b8d1e03049c5092d705bcd3ce369f02a9472f95 
[2]
$ ./check nvme/003
nvme/003 (test if we're sending keep-alives to a discovery controller) [failed]
runtime  11.344s  ...  11.346s
--- tests/nvme/003.out	2024-01-10 04:03:21.975035862 +0100
+++ /root/blktests/results/nodev/nvme/003.out.bad	2024-01-10 07:19:46.978193215 +0100
@@ -1,3 +1,4 @@
Running nvme/003
+connecting to device: nvme0
disconnected 1 controller(s)
Test complete
> nvme/rc: don't print the nvme connect msg

- tests/nbd/001
- tests/nbd/001.out
lsblk -n ouput format changed due to the substantial changes
in libsmartcols, which lsblk relies on for generating output,
fix it by using the raw format
Fixes: #132
> nbd/001: change to use lsblk raw output format

- tests/block/035
Make it easier to retrieve the IOPS results by reporting these on stdout.
Suggested-by: Shin'ichiro Kawasaki <shinichiro.kawasaki@wdc.com>
> block/035: Report IOPS

- tests/zbd/012
- tests/zbd/012.out
Test concurrent requeuing of zoned writes and request queue freezing. While this test passes with kernel 6.9, it triggers a hang with kernels 6.10..6.12. This shows that this hang is a regression introduced by the zone write plugging code.
sysrq: Show Blocked State
task:(udev-worker)   state:D stack:0     pid:75392 tgid:75392 ppid:2178   flags:0x00000006
Call Trace:
<TASK>
__schedule+0x3e8/0x1410
schedule+0x27/0xf0
blk_mq_freeze_queue_wait+0x6f/0xa0
queue_attr_store+0x60/0xc0
kernfs_fop_write_iter+0x13e/0x1f0
vfs_write+0x25b/0x420
ksys_write+0x65/0xe0
do_syscall_64+0x82/0x160
entry_SYSCALL_64_after_hwframe+0x76/0x7e
> zbd/012: Test requeuing of zoned writes and queue freezing

- tests/throtl/002
- tests/throtl/003
On 64k ppc64le kernel, the max_sectors should be set by (64k/512), or it will trigger below WARNING:
[  299.201428] ------------[ cut here ]------------ [  299.201453] WARNING: CPU: 3 PID: 4680 at block/blk-settings.c:286 blk_validate_limits+0x440/0x540 [  299.201471] Modules linked in: null_blk bonding tls rfkill ibmveth sg pseries_rng vmx_crypto fuse loop nfnetlink xfs sd_mod ibmvscsi scsi_transport_srp dm_mirror dm_region_hash dm_log dm_mod [  299.201508] CPU: 3 UID: 0 PID: 4680 Comm: bash Kdump: loaded Not tainted 6.13.0-0.rc2.22.eln144.ppc64le #1 [  299.201517] Hardware name: IBM,9009-22A POWER9 (architected) 0x4e0202 0xf000005 of:IBM,FW910.00 (VL910_062) hv:phyp pSeries [  299.201523] NIP:  c00000000098ccc0 LR: c000000000987280 CTR: 0000000000000000
[  299.201529] REGS: …
> throtl/{002,003}: update max_sectors setting

- tests/nvme/049
Update the error info check string:
check: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=io_uring_cmd, iodepth=1 fio-3.38-16-g6f3de
Starting 1 process
fio: pid=9638, err=1/file:engines/io_uring.c:1272, func=io_queue_init, error=Operation not permitted
Run status group 0 (all jobs):
> nvme/049: update fio_output msg check for io_uring_cmd support

- tests/nvme/056
Fixes a shell syntax error that occurs when trying to perform bitwise AND operation on empty ddp capabilities.
Now explicitly checks if ddp_caps hw returns empty string before proceeding with capability check.
Improves error handling for non-ddp capable devices like qemu virtio-net.
Without this patch qemu with virtio-net returns error:
```
tests/nvme/056: line 222: & 3: syntax error: operand expected (error token is "& 3")
```
With patch:
```
nvme/056 (tr=tcp) (enable zero copy offload and run rw traffic) [not run]
runtime    ...  0.150s
No ddp capabilities found for enp0s6
```
> nvme/056: Add check for empty ddp capabilities

- common/nvme
The local wwnn and wwpn don't need a port offset.
WARNING: Test did not clean up port: 0
common/nvme: line 172: _local_wwnn: command not found
common/nvme: line 172: _local_wwpn: command not found
WARNING: Test did not clean up subsystem: blktests-subsystem-1
> common/nvme: use correct local wwnn/wwpn for rport removal

- src/Makefile
When cross-building we need to pass the correct paths via CFLAGS to be able to find extra libraries. We could convert to using pkg-config to resolve library availability but as the rest of the build doesn't need it we can just ensure the same CFLAGS used for building are used in the probe macros.
> src/Makefile: include CFLAGS in probe macros

- tests/loop/011
CKI reported random loop/011 failure, fix it by using lazy umount for tmpfs.
$ ./check loop/011
loop/011 (Make sure unsupported backing file fallocate does not fill dmesg with errors) loop/011 (Make sure unsupported backing file fallocate does not fill dmesg with errors) [failed]
runtime  0.148s  ...  0.145sults/tmpdir.loop.011.QiG/tmpfs': Device or resource busy
--- tests/loop/011.out	2025-06-09 03:49:23.017287762 +0000
+++ /root/blk/results/nodev/loop/011.out.bad	2025-06-09 04:26:22.645147858 +0000
@@ -1,3 +1,4 @@
Running loop/011
+umount: /root/blk/results/tmpdir.loop.011.QiG/tmpfs: target is busy.
Found 1 error(s) in dmesg
Test complete
$ mount | grep loop
testfs on /root/blk/results/tmpdir.loop.011.t7M/tmpfs type tmpfs (rw,relatime,seclabel,inode64)
> loop/011: use lazy umount for tmpfs

- tests/loop/006
$ ./check loop/006
loop/006 (change loop backing file while creating/removing another loop device) [failed]
runtime  31.526s  ...  31.036s
--- tests/loop/006.out	2025-07-15 06:27:41.485609277 -0400
+++ /root/blktests/results/nodev/loop/006.out.bad	2025-07-18 06:59:18.916498155 -0400
@@ -1,2 +1,3 @@
Running loop/006
+tests/loop/006: line 66: 700070 Killed                     run_setter "$loop_dev"
Test complete
Link: https://github.com/linux-blktests/blktests/issues/191
> loop/006: fix the test failure with Bash 5.3
